### ISSUE TITLE
 Poetry could not find a pyproject.toml file in /github/workspace or its parents

### ISSUE THREAD

**Issue by baselakasha** [JRubics/poetry-publish#19]
Hello, I am getting this error although I have a pyproject.toml in the root of my project:
```
 Poetry could not find a pyproject.toml file in /github/workspace or its parents
```

My `.github\workflows\build-and-push.yml`:

```
name: build_and_push
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
```

**Comment by baselakasha** [comment]
There was something wrong with my workflow file. I have replaced it with the provided example and it works. 

``` 
name: Python package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.10
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
```
