### ISSUE TITLE
'There is no pypi-token.testpypi setting.'

### ISSUE THREAD

**Issue by elizaaverywilson** [JRubics/poetry-publish#25]
I'm getting the following error when I try to publish:

`There is no pypi-token.testpypi setting.`

My GitHub action is:

```
name: Publish to TestPyPi
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.TESTPYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
```

Am I doing something wrong? I have a secret TESTPYPI_TOKEN in the GitHub environment. I'm new to docker and not sure how to debug or research this further.
