### ISSUE TITLE
Build with poetry-dynamic-versioning-plugin failure

### ISSUE THREAD

**Issue by NickSebClark** [JRubics/poetry-publish#41]
Hello trying this out but running into a problem.

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          plugins: "poetry-dynamic-versioning-plugin"
```
Is what my yaml looks like but i get this:

```
Using version ^0.4.0 for poetry-dynamic-versioning-plugin

Updating dependencies
Resolving dependencies...

Package operations: 4 installs, 0 updates, 0 removals

  • Installing markupsafe (2.1.3)
  • Installing dunamai (1.18.0)
  • Installing jinja2 (3.1.2)
  • Installing poetry-dynamic-versioning-plugin (0.4.0)

Writing lock file

No module named 'poetry.core.semver'
```

Any ideas?
