### ISSUE TITLE
Publish to PyPI via OIDC

### ISSUE THREAD

**Issue by Josverl** [JRubics/poetry-publish#45]
How can I publish using PyPI trusted publishers / OIDC ?

I tried using a separate action to get a token, that runs without a problem ,  
but publishing still fails on auth with `HTTP Error 403: Invalid or non-existent authentication information. `

```yml
name: Python package to pypi via OIDC
on:
  push:
    tags:
      - "v*.*.*-*"
      - "v*.*.*"
  workflow_dispatch:
jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    # environment: release    
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.2

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: "${{ steps.mint.outputs.api-token }}"
``` 

accoding to the [pypi docs](https://docs.pypi.org/trusted-publishers/)
the username is supposed to be "__token__", but I cannot find how to make this work with this action 
```
          repository_username: "__token__"
          repository_password: "${{ steps.mint.outputs.api-token }}"
```
also fails 

[logs >](https://github.com/Josverl/micropython-magic/actions/runs/7567458084/job/20606707652)
